services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=DemoCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_LISTEN_ADDRESS=0.0.0.0
    networks:
      cassandra_net:
        aliases:
          - cassandra1

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    depends_on:
      - cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=DemoCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra2
      - CASSANDRA_LISTEN_ADDRESS=0.0.0.0
    networks:
      cassandra_net:
        aliases:
          - cassandra2

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    depends_on:
      - cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=DemoCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra3
      - CASSANDRA_LISTEN_ADDRESS=0.0.0.0
    networks:
      cassandra_net:
        aliases:
          - cassandra3

networks:
  cassandra_net:
    driver: bridge
